title: AFUP Montpellier
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
future: true

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml

paginate: 10
paginate_path: "blog/page-:num/"
permalink: blog/:title/

navigation:
  - title: Blog
    url: /
  - title: Meetups
    url: /meetups
  - title: A propos
    url: /a-propos
  - title: Contact
    url: /contact

collections:
  meetups:
    output: true

social:
  twitter: afup_mtp
  facebook: AFUPmontpellier
  github: afup-montpellier

google_analytics: "UA-******-1"
